#!/usr/bin/env sh

. ${HOME}/.bashrc

source ${HOME}/.alias

if [ -d "$HOME/etc/bash_completion.d" ] ; then
	. $HOME/etc/bash_completion.d/*.bash
fi

if [ -f /etc/bash_completion ] ; then
	. /etc/bash_completion
fi

export PATH="$HOME/.cargo/bin:$PATH"

if [[ "$OSTYPE" == "darwin"* ]]
then
    eval "$(/opt/homebrew/bin/brew shellenv)"
    export BASH_SILENCE_DEPRECATION_WARNING=1
    export TERM=xterm-256color
fi

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/ak/.lmstudio/bin"
export PATH="/opt/homebrew/opt/python@3.12/libexec/bin:$PATH"
export CLOUDSDK_PYTHON="/opt/homebrew/bin/python3.12"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/ak/Downloads/google-cloud-sdk/path.bash.inc' ]; then . '/Users/ak/Downloads/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/ak/Downloads/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/ak/Downloads/google-cloud-sdk/completion.bash.inc'; fi
