#!/usr/bin/env sh

. ${HOME}/.bashrc

source ${HOME}/.alias

if [ -d "$HOME/etc/bash_completion.d" ] ; then
	. $HOME/etc/bash_completion.d/*.bash
fi

if [ -f /etc/bash_completion ] ; then
	. /etc/bash_completion
fi

export PATH="$HOME/.cargo/bin:$PATH"
eval "$(/opt/homebrew/bin/brew shellenv)"
export BASH_SILENCE_DEPRECATION_WARNING=1
